### ISSUE TITLE
All-Contributors

### ISSUE THREAD

**Issue by SuperCoderDamian** [P2PHackClub/PixTools#16]
@all-contributors please add @SuperCoderDamian for code and bug and data

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for bug and data

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for example and ideas

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for maintenance

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for projectManagement

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for security and tool and test

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for security and tool

**Comment by SuperCoderDamian** [comment]
@all-contributors please add @SuperCoderDamian for infra

**Comment by thatrobotdev** [comment]
PR #18 merged
